server:
  port: 8080
  servlet:
    context-path: /myapp
  jetty:
    threads:
      acceptors: 2
      selectors: 4

spring:
  mvc:
    view:
      suffix: .html
      static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/mydb.db
    username:
    password:

  jpa:
    database-platform: com.example.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
