server:
  port: 8080
  servlet:
    context-path: /myapp
  jetty:
    threads:
      acceptors: 2
      selectors: 4

spring:
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path: classpath:/templates

  mvc:
#    view:
#      suffix: .html
    static-path-pattern: /**

  web:
    resources:
      # 静态资源路径（重要）
      static-locations: classpath:/templates/,classpath:/static/

  datasource:
    driver-class-name: org.sqlite.JDBC
    # 使用相对路径
    url: jdbc:sqlite::resource:static/sqlite/mydb.db
    username:
    password:

  jpa:
    # 手动添加SQLiteDialect
    database-platform: com.example.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    # 是否显示执行的SQL语句
    show-sql: false
